---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create container network
      containers.podman.podman_network:
        name: molecule-linux-test
        state: present
    - name: Create test containers
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command }}"
        privileged: "{{ item.privileged }}"
        state: started
        network: molecule-linux-test
        systemd: true
        log_driver: json-file
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
