---
- name: Destroy molecule containers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Stop and remove container
      containers.podman.podman_container:
        name: "{{ item.name }}"
        state: absent
        auto_remove: true
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
    - name: Remove container network
      containers.podman.podman_network:
        name: molecule-linux-test
        state: absent
