---
- name: Update web servers
  hosts: webservers
  become: false
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ required_packages }}"

    - name: Installing httpd server
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Write the apache config file
      ansible.builtin.template:
        src: httpd.conf.j2
        dest: /etc/httpd.conf
        mode: "0644"

- name: Update db servers
  hosts: databases
  become: false

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ required_packages }}"

    - name: Ensure postgresql is at the present version
      ansible.builtin.dnf:
        name: postgresql
        state: present
